name: Deploy to Surge

on:
  push:
    branches:
      - main

  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Surge.sh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Node.js for front-end dependencies (if applicable)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust the version according to your project requirements

      # Install dependencies if your project needs it (optional)
      - name: Install dependencies
        run: npm install # Only required if you are using npm/yarn in your project

      # Build the project (optional if you need to build static assets)
      - name: Build project
        run: npm run build # Adjust this to your build command, or remove it if not needed

      # Deploy to Surge.sh
      - name: Deploy to Surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'nnt.surge.sh'  # Replace with your Surge domain
          project: '.'  # Path to your build folder or project root
          login: ${{ secrets.surge_login }}  # Add your Surge login as GitHub secret
          token: ${{ secrets.surge_token }}  # Add your Surge token as GitHub secret
